### ISSUE TITLE
Searches intermittently return nil instead of empty array

### ISSUE THREAD

**Issue by randallb** [sferik/twitter#410]
So I have a controller which processes Twitter searches. Occasionally, I get back `nil` instead of an array.

The error that I get back is:

```
undefined method `[]' for nil:NilClass
twitter (4.7.0) lib/twitter/client.rb:97:in `block in request_setup'
```

But that's happening because my `@client.search('query', optionsHash)` is returning `nil`.

I noticed this started happening when I upgraded to 4.7.0, from 4.5.0 i believe. (I wanted the application only auth, which, by the way, is totally awesome.)
