### ISSUE TITLE
Upgrading from twitter gem 1.6.0 to 4.0.0 error

### ISSUE THREAD

**Issue by jferrercas** [sferik/twitter#314]
Hi there

Thank you for twitter gem 4.0.0

I am upgrading my app to work with Twitter API v1.1.

Previous app environment was rails 3.1 and twitter gem 1.6.0. It works ok. 

I created a new app with rails 3.1 and twitter gem 4.0.0. 

Now when I execute rails server it shows this message

Action Controller: Exception caught
undefined method `new' for Twitter:Module
twitter (4.0.0) lib/twitter.rb:22:in`method_missing'

In my previous app I have

```
Twitter.configure do |config|
  config.consumer_key = 'XXXXXXX'
  config.consumer_secret = 'XXXXXXX'
end
```

I tried this and this one

```
Twitter.configure do |config|
  config.consumer_key = 'XXXXXXX'
  config.consumer_secret = 'XXXXXXX'
  config.oauth_token = 'XXXXXXXX'
  config.oauth_token_secret = 'XXXXXXXXX 
end
```

but same problem

In previous version I have in application_controller.rb

```
  def client
    @client = Twitter::Client.new(:oauth_token => session[:access_token], :oauth_token_secret => session[:access_secret])
  end
```

I tried with data from my Twitter application

```
  def client
    @client = Twitter::Client.new(:oauth_token => "XXXXXXX", :oauth_token_secret => "XXXXXXXXX")
  end
```

but same problem

What I can do to solve this? Thanks
